version: "3.4"

# Development environment override
services:
  php:
    build:
      target: api_customers_php_dev
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # See https://github.com/docker/for-linux/issues/264
      # The `remote_host` below may optionally be replaced with `remote_connect_back`
      # XDEBUG_MODE required for step debugging
      XDEBUG_MODE: debug
      # default port for Xdebug 3 is 9003
      # idekey=VSCODE if you are debugging with VSCode
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        idekey=PHPSTORM 
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=api-platform
    extra_hosts:
      - host.docker.internal:host-gateway  
      
#  pwa:
#    build:
#      context: ./pwa
#      target: api_platform_pwa_dev
#    volumes:
#      - ./pwa:/usr/src/pwa:rw,cached

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

  localstack-core:
    image: localstack/localstack:1.0.4
    environment:
      - SERVICES=s3
      # - EDGE_PORT=4566
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
#      - AWS_ACCESS_KEY_ID=test
#      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./.local_data/localstack:/var/lib/localstack
      - ./aws:/docker-entrypoint-initaws.d
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "4566:4566"

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
