knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            aws_s3:
                service_id: 'ct_file_store.s3'
                bucket_name: "%env(AMAZON_S3_BUCKET_NAME)%"
                detect_content_type: true
                options:
                    create: true
                    directory: 'images'
    filesystems:
        image_fs:
            adapter: image_adapter
