vich_uploader:
    db_driver: orm
    
    metadata:
            type: attribute

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    storage: gaufrette
    mappings:
        image:
            inject_on_load: true
            #uri_prefix: /images
            #upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            uri_prefix: "%env(AMAZON_S3_ENDPOINT)%/%env(AMAZON_S3_BUCKET_NAME)%/images"
            upload_destination: image_fs
            delete_on_update: false
            delete_on_remove: false 
